services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./database:/var/www/database
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    user: www-data

volumes:
  composer_cache: